### ISSUE TITLE
3D preview does not work as expected when window size changed from small to large

### ISSUE THREAD

**Issue by brownshui** [alexrj/Slic3r#2453]
![2014-12-26_132935](https://cloud.githubusercontent.com/assets/6380638/5555927/4498d888-8d03-11e4-9d55-5e3d1a52c830.jpg)

Slic3r V1.2.1, Windows 7 32-bit.
It can be reproduce by:
1. Open model in a small window.
2. Select the 3D preview tab.
3. Enlarge the window to maximum size.

But it will recover after hide the window and show it again.

**Comment by alexrj** [comment]
@brownshui, is this fixed as of 1.2.4?

**Comment by a4jp-com** [comment]
The models still get cut up when zooming after resizing. I think it is the same problem but the model doesn't get squished anymore.

![screen shot 01-04-15 at 09 40 pm](https://cloud.githubusercontent.com/assets/9621044/5605940/5f57f59c-945a-11e4-9e43-985a37211603.JPG)

**Comment by brownshui** [comment]
I had tested 1.2.4.
It works sometimes.
But after repeating normal and maximum window few times, it still got squished.
And it crashed after resize window very often.

**Comment by alexrj** [comment]
This looks fixed with 1.2.6. @brownshui can you confirm?

**Comment by brownshui** [comment]
Sorry for late confirmation.
I thank it was fixed in 1.2.6, although not perfect.
Thanks, Alexrj.

At the mean time, I found it crashed frequently according to my old configuration profile.
Once delete profile folder, I can generate gcode smoothly.

Please let me known If you want to get my slic3r profile for debugging purpose.
I can put it to somewhere or send you by mail.

**Comment by alexrj** [comment]
Hi, if you find a reproducible crash I'll be glad to look at it. But please collect all the info listed at https://github.com/alexrj/Slic3r/blob/master/CONTRIBUTING.md and open a new separate issue.
