### ISSUE TITLE
Crashing importing STL files in 1.2.5

### ISSUE THREAD

**Issue by TrevorTurner** [alexrj/Slic3r#2518]
I am experiencing slic3r crashing when importing STL files generated in FormZ. The application closes after selecting the file with 'Add'. Please provide me with a way to send you and example file that crashes on adding. I am using Windows 7 64 Bit. The same STL files will import into 1.1.7

**Comment by dexy31337** [comment]
@TrevorTurner (dropbox)[dropbox.com] is a good way of sharing files.

**Comment by dexy31337** [comment]
@TrevorTurner [Dropbox](http://www.dropbox.com) is a good way of sharing files.

**Comment by TrevorTurner** [comment]
It appears dropbox can only share with specific email addresses

**Comment by TrevorTurner** [comment]
An example of a file causing crashing on adding is:
https://www.dropbox.com/s/05m3hdrmrw193qp/strap1_6.stl?dl=0

**Comment by braddo99** [comment]
I also have a file which crashes 1.2.5 on Windows 7 64 on opening an STL file. Here is a link to the STL: https://www.dropbox.com/s/kcnxbvmq4kxnt5r/Brad_fixed.stl?dl=0

Here is the config file: 
https://www.dropbox.com/s/8nqmkd9yyqo6ncp/config_with_crash_on_open.ini?dl=0

**Comment by lordofhyphens** [comment]
@TrevorTurner Does it crash on 1.2.4 or 1.2.3? It's a lot fewer commits to walk through if it works with either of those two versions.

**Comment by dexy31337** [comment]
Just for info - I've opened both STL files on Mac and Win7x32 with no crash with 1.2.5.

**Comment by alexrj** [comment]
I think this might be related to #2517, so it needs to be tested with the upcoming 1.2.6.

**Comment by TrevorTurner** [comment]
Sorry did not get a chance yet to test on earlier versions yet. Will also test on 1,2.6 when it is available.

**Comment by alexrj** [comment]
Hello, can you confirm this is fixed in 1.2.6? Thank you!

**Comment by TrevorTurner** [comment]
Still crashing immediately on add in 1.2.6 on 64 Bit Windows 7

**Comment by TrevorTurner** [comment]
Also crashes on 1.2.3 64 Bit Windows 7

**Comment by alexrj** [comment]
I'm not able to reproduce this with 1.2.6 or 1.2.7-dev... :(

**Comment by braddo99** [comment]
I am still experiencing crashes with 126 but I think it is due to importing setting files from previous versions which are somehow incompatible. For example, I did a new install of 126, imported the settings file I linked above, then imported the linked stl file. Crash. However, if I delete the C:\Users\Me\Roaming\Slic3r folder, re-open without the settings (redo manually) then the file opens, exports and prints just fine.

**Comment by alexrj** [comment]
@TrevorTurner, @braddo99: this should be fixed with 1.2.7 finally.  Can you confirm so that we can close this report? Thank you in advance!

**Comment by braddo99** [comment]
OK, let me try to recreate the above...

**Comment by alexrj** [comment]
@braddo99, let me know if 1.2.9 fixes the issue and we can close this one. Thank you!

**Comment by alexrj** [comment]
@braddo99, no answer from you.  I assume this is fixed.
