### ISSUE TITLE
"Right-click -> Reload from disk" reloads wrong object and adds it instead of replacing it

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#3786]
### Version
1.3.0-dev 61c8359995e785a638d2f39390c2998a889b4a93

### Operating system type + version
Ubuntu 16.04

### Behavior
I have loaded an AMF plate, as described in #3785. It has two objects, one of which has a modifier and some separate parameters.

If I right-click one object and choose "Reload from Disk", I was a bit curious about what would happen. The AMF contains the original STL file name, but would that be reloaded or the entire AMF or just this object from the AMF? It's not really obvious given the situation.

Anyway, I'm not really sure what happens but Slic3r appears to add the other object once more, and place it on top of the selected object. Pictures will describe this better. Here's a screenshot before reloading:

![before-reload](https://cloud.githubusercontent.com/assets/684832/24150387/e4ad88f8-0e45-11e7-9cb8-fb785d6d50cd.png)

and below is what it looks like after reloading, when I right click on the smaller part on the left to reload. If I right click the part on the right, the smaller part is overlaid on top of that instead, so it's always the other part that is placed on top of the selected part.

![after-reload](https://cloud.githubusercontent.com/assets/684832/24150406/ef7442cc-0e45-11e7-8e4b-0f32552a324f.png)

### Test files

Regarding test files, I'm not sure if I need all STLs in addition to the AMF, or how this process really works, so I'm not uploading anything right now.

**Comment by alexrj** [comment]
Good catch.

**Comment by alexrj** [comment]
Fixed. Thank you!

**Comment by kefir-** [comment]
Thanks! But perhaps there should be some clarification of what is reloaded, I'm still not sure. :-) Is the original STL file reloaded?
