### ISSUE TITLE
Honeycomb infill ignore "Combine infill every [1] layers."

### ISSUE THREAD

**Issue by AndKe** [alexrj/Slic3r#4345]
### Version
1.3.0dev (26feb)

### Operating system type + version
Ubuntu 17.10

### Behavior
with: "Combine infill every [1] layers."
Any type infill is printed on every Z level, as expected.
Except Honeycomb,  It will print it's perimeters every third layer, maybe with insufficient filament, so it's mostly gone - and barely visible or not existing in reality.

![screenshot from 2018-03-17 08-01-11](https://user-images.githubusercontent.com/1468842/37552674-2e0c9968-29ba-11e8-99c8-acd3232199c5.png)

### STL

[temp.zip](https://github.com/alexrj/Slic3r/files/1821451/temp.zip)

**Comment by lordofhyphens** [comment]
Was pretty sure I fixed this for regular honeycomb months ago.

Also: The preview lies a bit about the actual flow. Could you provide a photo as well of a print where this is going on?

**Comment by lordofhyphens** [comment]
@bubnikv have you noticed this in the Prusa3d fork? I remember having to boost the flow when this was all done in Perl. 

#3410 #1783

**Comment by AndKe** [comment]
@lordofhyphens too late for photo, I threw those prints away long time ago.

The issue is very real , I discovered it "in reverse" :  First saw some prints with top layer being surprisingly less supported /dense on edges , did not mind it that much, then I dropped by the workshop as the printer printed one with "bad" infill, I stopped it, thinking something was wrong - then discovered that only some walls of infill had this issue, then verified using OctoPi Gcode viewer, and lastly using Slic3r preview. - which I posted.

**Comment by lordofhyphens** [comment]
@AndKe I think I've got it fixed now, could you give it a try in the next build?

**Comment by lordofhyphens** [comment]
![image](https://user-images.githubusercontent.com/31754/38180175-190bc970-35f0-11e8-9b07-ba8cf4ca5dc0.png)

**Comment by AndKe** [comment]
@lordofhyphens I downloaded the current dev build with timestamp 2 April , 04:22
Same issue remain, it can also can be seen in the screenshot of preview that you posted 4 hour ago.
-dev builds should have some git /build tag info in about screen.

**Comment by lordofhyphens** [comment]
The "missing" layers on the edges are an artifact of honeycomb, not infill every N.

**Comment by lordofhyphens** [comment]
![image](https://user-images.githubusercontent.com/31754/38196580-7e50509a-3649-11e8-9154-49dc3e60011a.png)
Here it is at N=1. Better to open a separate issue for it.

**Comment by lordofhyphens** [comment]
The download has the git commit in it by the way; 4db029c is the commit with the change for this issue in it.

**Comment by lordofhyphens** [comment]
#4359 for reference. I'm locking this now.
